name: mzad_damascus
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  responsive_sizer: ^3.3.1
  easy_localization: ^3.0.5
  shared_preferences: ^2.2.3
  http: ^1.1.0
  get_it: ^7.6.4
  file_picker:

  connectivity_plus: ^5.0.1
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter_exit_app: ^1.1.2
  dropdown_button2: ^2.3.9
  dynamic_height_grid_view: ^0.0.4
  flash: ^3.1.1
  pinput: ^4.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  dots_indicator: ^3.0.0
  carousel_slider: ^5.0.0
  country_code_picker: ^2.0.0
  pin_code_text_field: ^1.8.0
#  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/gifs/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.otf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

